postsubmits:
  rajaskakodkar/tanzu-test-infra:
  - name: post-image-builder
    cluster: prow-build
    decorate: true
    max_concurrency: 1
    branches:
    - ^main$
    run_if_changed: '^images/image-build*'
    annotations:
      testgrid-dashboards: testing-images
      testgrid-tab-name: post-image-builder
    labels:
      preset-registry-credentials: "true"
      preset-dind-enabled: "true"
      preset-aws-credentials: "true"
    spec:
      containers:
      - image: REGISTRY_PUSH/image-builder:v20220803-dccc121
        command:
        - /usr/local/bin/run.sh
        args:
        - images/image-builder
        - REGISTRY_PUSH/image-builder
        securityContext:
          privileged: true
  - name: post-test-image
    cluster: prow-build
    decorate: true
    max_concurrency: 1
    branches:
    - ^main$
    run_if_changed: '^images/test-image*'
    annotations:
      testgrid-dashboards: testing-images
      testgrid-tab-name: post-test-image
    labels:
      preset-registry-credentials: "true"
      preset-dind-enabled: "true"
      preset-aws-credentials: "true"
    spec:
      containers:
      - image: REGISTRY_PUSH/image-builder:v20220803-dccc121
        command:
        - /usr/local/bin/run.sh
        args:
        - images/test-image
        - REGISTRY_PUSH/test-image
        securityContext:
          privileged: true
