apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: registry-username
  namespace: test-pods
spec:
  backendType: secretsManager
  region: us-east-2
  roleArn: SECRETS_ROLE_ARN
  data:
    - key: registry/username
      name: username
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: registry-password
  namespace: test-pods
spec:
  backendType: secretsManager
  region: us-east-2
  roleArn: SECRETS_ROLE_ARN
  data:
    - key: registry/password
      name: password
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: aws-access-key-id
  namespace: test-pods
spec:
  backendType: secretsManager
  region: us-east-2
  roleArn: SECRETS_ROLE_ARN
  data:
    - key: aws-access-key-id
      name: aws-access-key-id
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: aws-access-key-secret
  namespace: test-pods
spec:
  backendType: secretsManager
  region: us-east-2
  roleArn: SECRETS_ROLE_ARN
  data:
    - key: aws-access-key-secret
      name: aws-access-key-secret
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: aws-b64encoded-credential
  namespace: test-pods
spec:
  backendType: secretsManager
  region: us-east-2
  roleArn: SECRETS_ROLE_ARN
  data:
    - key: aws-b64encoded-credential
      name: aws-b64encoded-credential
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: aws-ssh-key-name
  namespace: test-pods
spec:
  backendType: secretsManager
  region: us-east-2
  roleArn: SECRETS_ROLE_ARN
  data:
    - key: aws-ssh-key-name
      name: aws-ssh-key-name
