---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cookie
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-service-secretstore
    kind: ClusterSecretStore
  target:
    name: cookie
    creationPolicy: Owner
  data:
  - secretKey: secret
    remoteRef:
      key: cookie
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcs-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-service-secretstore
    kind: ClusterSecretStore
  target:
    name: gcs-credentials
    creationPolicy: Owner
  data:
  - secretKey: "service-account.json"
    remoteRef:
      key: gcs-publisher
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oauth-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-service-secretstore
    kind: ClusterSecretStore
  target:
    name: github-oauth-config
    creationPolicy: Owner
  data:
  - secretKey: secret
    remoteRef:
      key: github-oauth-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-service-secretstore
    kind: ClusterSecretStore
  target:
    name: github-token
    creationPolicy: Owner
  data:
  - secretKey: appid
    remoteRef:
      key: appid
  - secretKey: cert
    remoteRef:
      key: github-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hmac-token
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-service-secretstore
    kind: ClusterSecretStore
  target:
    name: hmac-token
    creationPolicy: Owner
  data:
  - secretKey: hmac
    remoteRef:
      key: hmac-token
