postsubmits:
  rajaskakodkar/prow-on-tce:
  - name: build-test-image
    decorate: true
    run_if_changed: "images/test/.*"
    branches:
    - ^main$
    annotations:
      testgrid-dashboards: build-images
      testgrid-tab-name: Building test images
    spec:
      containers:
      - name: docker-build
        image: docker:20.10.12-dind
        command:
        - ./scripts/ci-docker-build-image.sh
        args:
        - ./images/dind-go-kubectl
        securityContext:
          privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      volumes:
      - name: dind-storage
        emptyDir: {}

periodics:
- name: periodic-build-test-image
  decorate: true
  interval: 24h
  extra_refs:
  - org: vagator
    repo: test-infra
    base_ref: main
  annotations:
    testgrid-dashboards: build-images
    testgrid-tab-name: periodics
  spec:
    containers:
    - name: docker-build
      image: docker:20.10.12-dind
      command:
      - ./scripts/ci-docker-build-image.sh
      args:
      - ./images/dind-go-kubectl
      securityContext:
        privileged: true
      env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
      - name: DOCKER_HOST
        value: tcp://localhost:2375
      volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
    volumes:
    - name: dind-storage
      emptyDir: {}
