postsubmits:
  rajaskakodkar/tanzu-test-infra:
  - name: build-test-image
    cluster: prow-build
    decorate: true
    run_if_changed: "images/test/.*"
    branches:
    - ^main$
    annotations:
      testgrid-dashboards: testing-images
      testgrid-tab-name: Building Dind image
    spec:
      containers:
      - name: docker-build
        image: docker:20.10.12-dind
        command:
        - ./scripts/ci-docker-build-image.sh
        args:
        - ./images/dind-go-kubectl
        securityContext:
          privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      volumes:
      - name: dind-storage
        emptyDir: {}
